export const SETTINGS = {
  API_URL_VERSION: 1, // 2 for local, 1 for server
  WEEK_SELECTOR: {
    DURATION_LOW_MINUTES: 1080, 
    DURATION_MEDIUM_MINUTES: 1320, 
  },
  DASHBOARD: {
    REQUIRED_XP: 100,
    REQUIRED_ACCOUNTED_TIME_MINUTES: 1080, 
  },
}; 